### ISSUE TITLE
Unable to add an additional subnet for a single hub

### ISSUE THREAD

**Issue by luke-taylor** [Azure/terraform-azurerm-caf-enterprise-scale#604]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.1

**azure provider**: 3.41.0

**module**: 3.1.2

#### Describe the bug
For the variable named `configure_connectivity_resources`  when adding an additional subnet in **ONE** of the hubs only it generates the following error:

```
│ Error: Invalid value for input variable
│ 
│   on ../modules/terraform-azurerm-caf-enterprise-scale/main.tf line 75, in module "connectivity_resources":
│   75:   settings        = local.configure_connectivity_resources.settings
│ 
│ The given value is not suitable for
│ module.enterprise_scale.module.connectivity_resources.var.settings declared
│ at
│ ../modules/terraform-azurerm-caf-enterprise-scale/modules/connectivity/variables.tf:44,1-20:
│ element types must all match for conversion to list.
╵
##[warning]Can't find loc string for key: TerraformPlanFailed
##[error]Error: TerraformPlanFailed 1

``` 

It has been noted that upon applying additional subnets to **all** hubs successfully generates a plan, thus it seems like a symmetry error. 

#### Steps to Reproduce

1. Install all necessary prerequisite tools.
2. Use the following code for the `configure_connectivity_resources` variable:
```
configure_connectivity_resources = {
    settings = {
      hub_networks = [
        {
          enabled = true
          config = {
            address_space                = ["10.100.0.0/16", ]
            location                     = "uksouth"
            link_to_ddos_protection_plan = false
            dns_servers                  = []
            bgp_community                = ""
            subnets                      = [
                {
                    name = "sn-alz"
                    address_prefixes = ["10.100.2.0/24",]
                }
            ]
            virtual_network_gateway = {
              enabled = false
              config = {
                address_prefix           = "10.100.1.0/24"
                gateway_sku_expressroute = "ErGw2AZ"
                gateway_sku_vpn          = ""
              }
            }
            azure_firewall = {
              enabled = true
              config = {
                address_prefix   = "10.100.0.0/24"
                enable_dns_proxy = true
                availability_zones = {
                  zone_1 = true
                  zone_2 = true
                  zone_3 = true
                }
              }
            }
            spoke_virtual_network_resource_ids      = []
            enable_outbound_virtual_network_peering = true
          }
        },
        {
          enabled = true
          config = {
            address_space                = ["10.200.0.0/16", ]
            location                     = "ukwest"
            link_to_ddos_protection_plan = false
            dns_servers                  = []
            bgp_community                = ""
            subnets                      = []
            virtual_network_gateway = {
              enabled = false
              config = {
                address_prefix           = "10.200.1.0/24"
                gateway_sku_expressroute = ""
                gateway_sku_vpn          = "VpnGw2AZ"
              }
            }
            azure_firewall = {
              enabled = false
              config = {
                address_prefix   = ""
                enable_dns_proxy = true
                availability_zones = {
                  zone_1 = true
                  zone_2 = true
                  zone_3 = true
                }
              }
            }
            spoke_virtual_network_resource_ids      = []
            enable_outbound_virtual_network_peering = true
          }
        },
      ]
      vwan_hub_networks = []
      ddos_protection_plan = {
        enabled = false
        config = {
          location = "UK South"
        }
      }
      dns = {
        enabled = true
        config = {
          location = null
          enable_private_link_by_service = {
            azure_automation_webhook             = true
            azure_automation_dscandhybridworker  = true
            azure_sql_database_sqlserver         = true
            azure_synapse_analytics_sqlserver    = true
            azure_synapse_analytics_sql          = true
            storage_account_blob                 = true
            storage_account_table                = true
            storage_account_queue                = true
            storage_account_file                 = true
            storage_account_web                  = true
            azure_data_lake_file_system_gen2     = true
            azure_cosmos_db_sql                  = true
            azure_cosmos_db_mongodb              = true
            azure_cosmos_db_cassandra            = true
            azure_cosmos_db_gremlin              = true
            azure_cosmos_db_table                = true
            azure_database_for_postgresql_server = true
            azure_database_for_mysql_server      = true
            azure_database_for_mariadb_server    = true
            azure_key_vault                      = true
            azure_kubernetes_service_management  = true
            azure_search_service                 = true
            azure_container_registry             = true
            azure_app_configuration_stores       = true
            azure_backup                         = true
            azure_site_recovery                  = true
            azure_event_hubs_namespace           = true
            azure_service_bus_namespace          = true
            azure_iot_hub                        = true
            azure_relay_namespace                = true
            azure_event_grid_topic               = true
            azure_event_grid_domain              = true
            azure_web_apps_sites                 = true
            azure_machine_learning_workspace     = true
            signalr                              = true
            azure_monitor                        = true
            cognitive_services_account           = true
            azure_file_sync                      = true
            azure_data_factory                   = true
            azure_data_factory_portal            = true
            azure_cache_for_redis                = true
          }
          private_link_locations                                 = ["ukwest","uksouth"]
          public_dns_zones                                       = []
          private_dns_zones                                      = ["contoso.private"]
          enable_private_dns_zone_virtual_network_link_on_hubs   = true
          enable_private_dns_zone_virtual_network_link_on_spokes = true
        }
      }
    }

    location = "uksouth"
    tags = {
        "Location" = "UK South"
        "Environment" = "Prod"
    }
    advanced = null
  }
```

**Comment by krowlandson** [comment]
Thank you for reporting this @luke-taylor. We have been able to reproduce this and I was able to work out a relatively simple fix within the module, although it felt a bit of a hack.

Upon further investigation what we observed is that Terraform appears to mishandle the object types when passing from parent to child module, and we were able to reproduce in a simple data model. I have since found the following similar issue which resulted in a fix which also resolves this issue:

- https://github.com/hashicorp/terraform/issues/31924

This was caused by a bug in the upstream go-cty library.

As such, we feel the best course of action is to recommend specifying a minimum Terraform version of `v1.3.3`.

Please try this and let us know how you get on 👍🏻 

For now we won't make any changes to the module or our guidance around supported Terraform versions, but we will consider this when we make the next major release.

cc: @matt-FFFFFF

**Comment by krowlandson** [comment]
👀 oh, and it turns out this bug has a regression in Terraform `v1.3.4` which results in the following:

```shell
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

inconsistent list element types (cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"address_prefix":cty.String, "azure_firewall":cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"availability_zones":cty.Object(map[string]cty.Type{"zone_1":cty.Bool, "zone_2":cty.Bool, "zone_3":cty.Bool}), "base_policy_id":cty.String, "dns_servers":cty.List(cty.String), "enable_dns_proxy":cty.Bool, "private_ip_ranges":cty.List(cty.String), "sku_tier":cty.String, "threat_intelligence_allowlist":cty.List(cty.String), "threat_intelligence_mode":cty.String}), "enabled":cty.Bool}), "enable_virtual_hub_connections":cty.Bool, "expressroute_gateway":cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"scale_unit":cty.Number}), "enabled":cty.Bool}), "location":cty.String, "routes":cty.List(cty.Object(map[string]cty.Type{"address_prefixes":cty.List(cty.String), "next_hop_ip_address":cty.String})), "secure_spoke_virtual_network_resource_ids":cty.List(cty.String), "sku":cty.String, "spoke_virtual_network_resource_ids":cty.List(cty.String), "vpn_gateway":cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"bgp_settings":cty.List(cty.Object(map[string]cty.Type{"asn":cty.Number, "instance_0_bgp_peering_address":cty.List(cty.Object(map[string]cty.Type{"custom_ips":cty.List(cty.String)})), "instance_1_bgp_peering_address":cty.List(cty.Object(map[string]cty.Type{"custom_ips":cty.List(cty.String)})), "peer_weight":cty.Number})), "routing_preference":cty.String, "scale_unit":cty.Number}), "enabled":cty.Bool})}), "enabled":cty.Bool}) then cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"address_prefix":cty.String, "azure_firewall":cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"availability_zones":cty.Object(map[string]cty.Type{"zone_1":cty.Bool, "zone_2":cty.Bool, "zone_3":cty.Bool}), "base_policy_id":cty.String, "dns_servers":cty.List(cty.String), "enable_dns_proxy":cty.Bool, "private_ip_ranges":cty.List(cty.String), "sku_tier":cty.String, "threat_intelligence_allowlist":cty.List(cty.String), "threat_intelligence_mode":cty.String}), "enabled":cty.Bool}), "enable_virtual_hub_connections":cty.Bool, "expressroute_gateway":cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"scale_unit":cty.Number}), "enabled":cty.Bool}), "location":cty.String, "routes":cty.List(cty.Object(map[string]cty.Type{"address_prefixes":cty.List(cty.String), "next_hop_ip_address":cty.String})), "secure_spoke_virtual_network_resource_ids":cty.List(cty.String), "sku":cty.String, "spoke_virtual_network_resource_ids":cty.List(cty.String), "vpn_gateway":cty.Object(map[string]cty.Type{"config":cty.Object(map[string]cty.Type{"bgp_settings":cty.List(cty.ObjectWithOptionalAttrs(map[string]cty.Type{"asn":cty.Number, "instance_0_bgp_peering_address":cty.List(cty.Object(map[string]cty.Type{"custom_ips":cty.List(cty.String)})), "instance_1_bgp_peering_address":cty.List(cty.Object(map[string]cty.Type{"custom_ips":cty.List(cty.String)})), "peer_weight":cty.Number}, []string{"instance_0_bgp_peering_address", "instance_1_bgp_peering_address"})), "routing_preference":cty.String, "scale_unit":cty.Number}), "enabled":cty.Bool})}), "enabled":cty.Bool}))
goroutine 14602 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23740a0, 0xc00639f650})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/zclconf/go-cty/cty.ListVal({0xc001327440, 0x3, 0x4?})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.0/cty/value_init.go:166 +0x42e
github.com/zclconf/go-cty/cty.transform({0xc00177ace0?, 0x2, 0x2}, {{{0x2d0fd38?, 0xc0062918f0?}}, {0x22824a0?, 0xc00602ff80?}}, {0x2cf70e8, 0xc000123f10})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.0/cty/walk.go:175 +0xf4a
github.com/zclconf/go-cty/cty.transform({0xc0062919a0?, 0x1, 0x1}, {{{0x2d0fda8?, 0xc006291900?}}, {0x23ac580?, 0xc0063890e0?}}, {0x2cf70e8, 0xc000123f10})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.0/cty/walk.go:220 +0x87c
github.com/zclconf/go-cty/cty.transform({0x0?, 0x0, 0x0}, {{{0x2d0fda8?, 0xc006291910?}}, {0x23ac580?, 0xc006389140?}}, {0x2cf70e8, 0xc000123f10})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.0/cty/walk.go:220 +0x87c
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.0/cty/walk.go:130
github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults).Apply(0xc000e14380?, {{{0x2d0fda8?, 0xc006291910?}}, {0x23ac580?, 0xc006389140?}})
        /home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.14.1/ext/typeexpr/defaults.go:38 +0xa7
github.com/hashicorp/terraform/internal/terraform.prepareFinalInputVariableValue({{0xc000ebb2c0, 0x1, 0x1}, {{}, {0xc000149440, 0x20}}}, 0xc00438fa58, 0xc000e4bba0)
        /home/circleci/project/project/internal/terraform/eval_variable.go:140 +0xaed
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).evalModuleVariable(0xc0063bb140?, {0x2d26478?, 0xc00186dc00?}, 0x3d?)
        /home/circleci/project/project/internal/terraform/node_module_variable.go:239 +0x545
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0xc0063bb140, {0x2d26478, 0xc00186dc00}, 0x2)
        /home/circleci/project/project/internal/terraform/node_module_variable.go:155 +0x172
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc002ec2000, {0x2d26478, 0xc00186dc00}, {0x21c4bd82200, 0xc0063bb140})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2544200, 0xc0063bb140})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0063bb1a0, {0x2544200, 0xc0063bb140}, 0xc0026ecd00)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf65
```

So maybe avoid that version too 🙄 

I can confirm that `v1.3.5` to `v1.3.7` all work as expected.

**Comment by luke-taylor** [comment]
Thanks for looking into this @krowlandson! Since this is an external issue and no module change is currently necessary as part of this particular issue I'll consider it closed.
